import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.preprocessing import StandardScaler
import joblib

# Parameters
file_path = r"Left_Joined_Dataset.csv"
chunksize = 10000  # Adjust chunk size based on your system's memory capacity
columns_to_drop = ['RenewFlag', 'CnclMo', 'NotCancFlag']
demographic_columns = ['ESTIMATE HOUSEHOLDS TOTAL', 'MOE HOUSEHOLDS TOTAL', 'ESTIMATE HOUSEHOLDS TOTAL - LESS THAN $10,000', 'MOE HOUSEHOLDS TOTAL - LESS THAN $10,000', 'ESTIMATE HOUSEHOLDS TOTAL - $10,000 TO $14,999', 'MOE HOUSEHOLDS TOTAL - $10,000 TO $14,999', 'ESTIMATE HOUSEHOLDS TOTAL - $15,000 TO $24,999', 'MOE HOUSEHOLDS TOTAL - $15,000 TO $24,999', 'ESTIMATE HOUSEHOLDS TOTAL - $25,000 TO $34,999', 'MOE HOUSEHOLDS TOTAL - $25,000 TO $34,999', 'ESTIMATE HOUSEHOLDS TOTAL - $35,000 TO $49,999', 'MOE HOUSEHOLDS TOTAL - $35,000 TO $49,999', 'ESTIMATE HOUSEHOLDS TOTAL - $50,000 TO $74,999', 'MOE HOUSEHOLDS TOTAL - $50,000 TO $74,999', 'ESTIMATE HOUSEHOLDS TOTAL - $75,000 TO $99,999', 'MOE HOUSEHOLDS TOTAL - $75,000 TO $99,999', 'ESTIMATE HOUSEHOLDS TOTAL - $100,000 TO $149,999', 'MOE HOUSEHOLDS TOTAL - $100,000 TO $149,999', 'ESTIMATE HOUSEHOLDS TOTAL - $150,000 TO $199,999', 'MOE HOUSEHOLDS TOTAL - $150,000 TO $199,999', 'ESTIMATE HOUSEHOLDS TOTAL - $200,000 OR MORE', 'MOE HOUSEHOLDS TOTAL - $200,000 OR MORE', 'ESTIMATE HOUSEHOLDS - MEDIAN INCOME (DOLLARS)', 'MOE HOUSEHOLDS - MEDIAN INCOME (DOLLARS)', 'ESTIMATE HOUSEHOLDS - MEAN INCOME (DOLLARS)', 'MOE HOUSEHOLDS - MEAN INCOME (DOLLARS)', 'ESTIMATE HOUSEHOLDS - HOUSEHOLD INCOME IN THE PAST 12 MONTHS', 'ESTIMATE FAMILIES TOTAL', 'MOE FAMILIES TOTAL', 'ESTIMATE FAMILIES TOTAL - LESS THAN $10,000', 'MOE FAMILIES TOTAL - LESS THAN $10,000', 'ESTIMATE FAMILIES TOTAL - $10,000 TO $14,999', 'MOE FAMILIES TOTAL - $10,000 TO $14,999', 'ESTIMATE FAMILIES TOTAL - $15,000 TO $24,999', 'MOE FAMILIES TOTAL - $15,000 TO $24,999', 'ESTIMATE FAMILIES TOTAL - $25,000 TO $34,999', 'MOE FAMILIES TOTAL - $25,000 TO $34,999', 'ESTIMATE FAMILIES TOTAL - $35,000 TO $49,999', 'MOE FAMILIES TOTAL - $35,000 TO $49,999', 'ESTIMATE FAMILIES TOTAL - $50,000 TO $74,999', 'MOE FAMILIES TOTAL - $50,000 TO $74,999', 'ESTIMATE FAMILIES TOTAL - $75,000 TO $99,999', 'MOE FAMILIES TOTAL - $75,000 TO $99,999', 'ESTIMATE FAMILIES TOTAL - $100,000 TO $149,999', 'MOE FAMILIES TOTAL - $100,000 TO $149,999', 'ESTIMATE FAMILIES TOTAL - $150,000 TO $199,999', 'MOE FAMILIES TOTAL - $150,000 TO $199,999', 'ESTIMATE FAMILIES TOTAL - $200,000 OR MORE', 'MOE FAMILIES TOTAL - $200,000 OR MORE', 'ESTIMATE FAMILIES - MEDIAN INCOME (DOLLARS)', 'MOE FAMILIES - MEDIAN INCOME (DOLLARS)', 'ESTIMATE FAMILIES - MEAN INCOME (DOLLARS)', 'MOE FAMILIES - MEAN INCOME (DOLLARS)', 'ESTIMATE FAMILIES - FAMILY INCOME IN THE PAST 12 MONTHS', 'ESTIMATE MARRIED-COUPLE FAMILIES TOTAL', 'MOE MARRIED-COUPLE FAMILIES TOTAL', 'ESTIMATE MARRIED-COUPLE FAMILIES TOTAL - LESS THAN $10,000', 'MOE MARRIED-COUPLE FAMILIES TOTAL - LESS THAN $10,000', 'ESTIMATE MARRIED-COUPLE FAMILIES TOTAL - $10,000 TO $14,999', 'MOE MARRIED-COUPLE FAMILIES TOTAL - $10,000 TO $14,999', 'ESTIMATE MARRIED-COUPLE FAMILIES TOTAL - $15,000 TO $24,999', 'MOE MARRIED-COUPLE FAMILIES TOTAL - $15,000 TO $24,999', 'ESTIMATE MARRIED-COUPLE FAMILIES TOTAL - $25,000 TO $34,999', 'MOE MARRIED-COUPLE FAMILIES TOTAL - $25,000 TO $34,999', 'ESTIMATE MARRIED-COUPLE FAMILIES TOTAL - $35,000 TO $49,999', 'MOE MARRIED-COUPLE FAMILIES TOTAL - $35,000 TO $49,999', 'ESTIMATE MARRIED-COUPLE FAMILIES TOTAL - $50,000 TO $74,999', 'MOE MARRIED-COUPLE FAMILIES TOTAL - $50,000 TO $74,999', 'ESTIMATE MARRIED-COUPLE FAMILIES TOTAL - $75,000 TO $99,999', 'MOE MARRIED-COUPLE FAMILIES TOTAL - $75,000 TO $99,999', 'ESTIMATE MARRIED-COUPLE FAMILIES TOTAL - $100,000 TO $149,999', 'MOE MARRIED-COUPLE FAMILIES TOTAL - $100,000 TO $149,999', 'ESTIMATE MARRIED-COUPLE FAMILIES TOTAL - $150,000 TO $199,999', 'MOE MARRIED-COUPLE FAMILIES TOTAL - $150,000 TO $199,999', 'ESTIMATE MARRIED-COUPLE FAMILIES TOTAL - $200,000 OR MORE', 'MOE MARRIED-COUPLE FAMILIES TOTAL - $200,000 OR MORE', 'ESTIMATE MARRIED-COUPLE FAMILIES - MEDIAN INCOME (DOLLARS)', 'MOE MARRIED-COUPLE FAMILIES - MEDIAN INCOME (DOLLARS)', 'ESTIMATE NONFAMILY HOUSEHOLDS TOTAL', 'MOE NONFAMILY HOUSEHOLDS TOTAL', 'ESTIMATE NONFAMILY HOUSEHOLDS TOTAL - LESS THAN $10,000', 'MOE NONFAMILY HOUSEHOLDS TOTAL - LESS THAN $10,000', 'ESTIMATE NONFAMILY HOUSEHOLDS TOTAL - $10,000 TO $14,999', 'MOE NONFAMILY HOUSEHOLDS TOTAL - $10,000 TO $14,999', 'ESTIMATE NONFAMILY HOUSEHOLDS TOTAL - $15,000 TO $24,999', 'MOE NONFAMILY HOUSEHOLDS TOTAL - $15,000 TO $24,999', 'ESTIMATE NONFAMILY HOUSEHOLDS TOTAL - $25,000 TO $34,999', 'MOE NONFAMILY HOUSEHOLDS TOTAL - $25,000 TO $34,999', 'ESTIMATE NONFAMILY HOUSEHOLDS TOTAL - $35,000 TO $49,999', 'MOE NONFAMILY HOUSEHOLDS TOTAL - $35,000 TO $49,999', 'ESTIMATE NONFAMILY HOUSEHOLDS TOTAL - $50,000 TO $74,999', 'MOE NONFAMILY HOUSEHOLDS TOTAL - $50,000 TO $74,999', 'ESTIMATE NONFAMILY HOUSEHOLDS TOTAL - $75,000 TO $99,999', 'MOE NONFAMILY HOUSEHOLDS TOTAL - $75,000 TO $99,999', 'ESTIMATE NONFAMILY HOUSEHOLDS TOTAL - $100,000 TO $149,999', 'MOE NONFAMILY HOUSEHOLDS TOTAL - $100,000 TO $149,999', 'ESTIMATE NONFAMILY HOUSEHOLDS TOTAL - $150,000 TO $199,999', 'MOE NONFAMILY HOUSEHOLDS TOTAL - $150,000 TO $199,999', 'ESTIMATE NONFAMILY HOUSEHOLDS TOTAL - $200,000 OR MORE', 'MOE NONFAMILY HOUSEHOLDS TOTAL - $200,000 OR MORE', 'ESTIMATE NONFAMILY HOUSEHOLDS - MEDIAN INCOME (DOLLARS)', 'MOE NONFAMILY HOUSEHOLDS - MEDIAN INCOME (DOLLARS)', 'ESTIMATE NONFAMILY HOUSEHOLDS - MEAN INCOME (DOLLARS)', 'MOE NONFAMILY HOUSEHOLDS - MEAN INCOME (DOLLARS)', 'ESTIMATE NONFAMILY HOUSEHOLDS - NONFAMILY INCOME IN THE PAST 12 MONTHS', 'ZIP_CODE', 'ESTIMATE TOTAL TOTAL POPULATION', 'MOE TOTAL TOTAL POPULATION', 'ESTIMATE TOTAL TOTAL POPULATION - UNDER 5 YEARS', 'MOE TOTAL TOTAL POPULATION - UNDER 5 YEARS', 'ESTIMATE TOTAL TOTAL POPULATION - 5 TO 9 YEARS', 'MOE TOTAL TOTAL POPULATION - 5 TO 9 YEARS', 'ESTIMATE TOTAL TOTAL POPULATION - 10 TO 14 YEARS', 'MOE TOTAL TOTAL POPULATION - 10 TO 14 YEARS', 'ESTIMATE TOTAL TOTAL POPULATION - 15 TO 19 YEARS', 'MOE TOTAL TOTAL POPULATION - 15 TO 19 YEARS', 'ESTIMATE TOTAL TOTAL POPULATION - 20 TO 24 YEARS', 'MOE TOTAL TOTAL POPULATION - 20 TO 24 YEARS', 'ESTIMATE TOTAL TOTAL POPULATION - 25 TO 29 YEARS', 'MOE TOTAL TOTAL POPULATION - 25 TO 29 YEARS', 'ESTIMATE TOTAL TOTAL POPULATION - 30 TO 34 YEARS', 'MOE TOTAL TOTAL POPULATION - 30 TO 34 YEARS', 'ESTIMATE TOTAL TOTAL POPULATION - 35 TO 39 YEARS', 'MOE TOTAL TOTAL POPULATION - 35 TO 39 YEARS', 'ESTIMATE TOTAL TOTAL POPULATION - 40 TO 44 YEARS', 'MOE TOTAL TOTAL POPULATION - 40 TO 44 YEARS', 'ESTIMATE TOTAL TOTAL POPULATION - 45 TO 49 YEARS', 'MOE TOTAL TOTAL POPULATION - 45 TO 49 YEARS', 'ESTIMATE TOTAL TOTAL POPULATION - 50 TO 54 YEARS', 'MOE TOTAL TOTAL POPULATION - 50 TO 54 YEARS', 'ESTIMATE TOTAL TOTAL POPULATION - 55 TO 59 YEARS', 'MOE TOTAL TOTAL POPULATION - 55 TO 59 YEARS', 'ESTIMATE TOTAL TOTAL POPULATION - 60 TO 64 YEARS', 'MOE TOTAL TOTAL POPULATION - 60 TO 64 YEARS', 'ESTIMATE TOTAL TOTAL POPULATION - 65 TO 69 YEARS', 'MOE TOTAL TOTAL POPULATION - 65 TO 69 YEARS', 'ESTIMATE TOTAL TOTAL POPULATION - 70 TO 74 YEARS', 'MOE TOTAL TOTAL POPULATION - 70 TO 74 YEARS', 'ESTIMATE TOTAL TOTAL POPULATION - 75 TO 79 YEARS', 'MOE TOTAL TOTAL POPULATION - 75 TO 79 YEARS', 'ESTIMATE TOTAL TOTAL POPULATION - 80 TO 84 YEARS', 'MOE TOTAL TOTAL POPULATION - 80 TO 84 YEARS', 'ESTIMATE TOTAL TOTAL POPULATION - 85 YEARS AND OVER', 'MOE TOTAL TOTAL POPULATION - 85 YEARS AND OVER', 'ESTIMATE TOTAL TOTAL POPULATION - 5 TO 14 YEARS', 'MOE TOTAL TOTAL POPULATION - 5 TO 14 YEARS', 'ESTIMATE TOTAL TOTAL POPULATION - 15 TO 17 YEARS', 'MOE TOTAL TOTAL POPULATION - 15 TO 17 YEARS', 'ESTIMATE TOTAL TOTAL POPULATION - UNDER 18 YEARS', 'MOE TOTAL TOTAL POPULATION - UNDER 18 YEARS', 'ESTIMATE TOTAL TOTAL POPULATION - 18 TO 24 YEARS', 'MOE TOTAL TOTAL POPULATION - 18 TO 24 YEARS', 'ESTIMATE TOTAL TOTAL POPULATION - 15 TO 44 YEARS', 'MOE TOTAL TOTAL POPULATION - 15 TO 44 YEARS', 'ESTIMATE TOTAL TOTAL POPULATION - 16 YEARS AND OVER', 'MOE TOTAL TOTAL POPULATION - 16 YEARS AND OVER', 'ESTIMATE TOTAL TOTAL POPULATION - 18 YEARS AND OVER', 'MOE TOTAL TOTAL POPULATION - 18 YEARS AND OVER', 'ESTIMATE TOTAL TOTAL POPULATION - 21 YEARS AND OVER', 'MOE TOTAL TOTAL POPULATION - 21 YEARS AND OVER', 'ESTIMATE TOTAL TOTAL POPULATION - 60 YEARS AND OVER', 'MOE TOTAL TOTAL POPULATION - 60 YEARS AND OVER', 'ESTIMATE TOTAL TOTAL POPULATION - 62 YEARS AND OVER', 'MOE TOTAL TOTAL POPULATION - 62 YEARS AND OVER', 'ESTIMATE TOTAL TOTAL POPULATION - 65 YEARS AND OVER', 'MOE TOTAL TOTAL POPULATION - 65 YEARS AND OVER', 'ESTIMATE TOTAL TOTAL POPULATION - 75 YEARS AND OVER', 'MOE TOTAL TOTAL POPULATION - 75 YEARS AND OVER', 'ESTIMATE TOTAL TOTAL POPULATION - MEDIAN AGE (YEARS)', 'MOE TOTAL TOTAL POPULATION - MEDIAN AGE (YEARS)', 'ESTIMATE TOTAL TOTAL POPULATION - SEX RATIO (MALES PER 100 FEMALES)', 'MOE TOTAL TOTAL POPULATION - SEX RATIO (MALES PER 100 FEMALES)', 'ESTIMATE TOTAL TOTAL POPULATION - AGE DEPENDENCY RATIO', 'MOE TOTAL TOTAL POPULATION - AGE DEPENDENCY RATIO', 'ESTIMATE TOTAL TOTAL POPULATION - OLD-AGE DEPENDENCY RATIO', 'MOE TOTAL TOTAL POPULATION - OLD-AGE DEPENDENCY RATIO', 'ESTIMATE TOTAL TOTAL POPULATION - CHILD DEPENDENCY RATIO', 'MOE TOTAL TOTAL POPULATION - CHILD DEPENDENCY RATIO', 'ESTIMATE PERCENT TOTAL POPULATION - UNDER 5 YEARS', 'MOE PERCENT TOTAL POPULATION - UNDER 5 YEARS', 'ESTIMATE PERCENT TOTAL POPULATION - 5 TO 9 YEARS', 'MOE PERCENT TOTAL POPULATION - 5 TO 9 YEARS', 'ESTIMATE PERCENT TOTAL POPULATION - 10 TO 14 YEARS', 'MOE PERCENT TOTAL POPULATION - 10 TO 14 YEARS', 'ESTIMATE PERCENT TOTAL POPULATION - 15 TO 19 YEARS', 'MOE PERCENT TOTAL POPULATION - 15 TO 19 YEARS', 'ESTIMATE PERCENT TOTAL POPULATION - 20 TO 24 YEARS', 'MOE PERCENT TOTAL POPULATION - 20 TO 24 YEARS', 'ESTIMATE PERCENT TOTAL POPULATION - 25 TO 29 YEARS', 'MOE PERCENT TOTAL POPULATION - 25 TO 29 YEARS', 'ESTIMATE PERCENT TOTAL POPULATION - 30 TO 34 YEARS', 'MOE PERCENT TOTAL POPULATION - 30 TO 34 YEARS', 'ESTIMATE PERCENT TOTAL POPULATION - 35 TO 39 YEARS', 'MOE PERCENT TOTAL POPULATION - 35 TO 39 YEARS', 'ESTIMATE PERCENT TOTAL POPULATION - 40 TO 44 YEARS', 'MOE PERCENT TOTAL POPULATION - 40 TO 44 YEARS', 'ESTIMATE PERCENT TOTAL POPULATION - 45 TO 49 YEARS', 'MOE PERCENT TOTAL POPULATION - 45 TO 49 YEARS', 'ESTIMATE PERCENT TOTAL POPULATION - 50 TO 54 YEARS', 'MOE PERCENT TOTAL POPULATION - 50 TO 54 YEARS', 'ESTIMATE PERCENT TOTAL POPULATION - 55 TO 59 YEARS', 'MOE PERCENT TOTAL POPULATION - 55 TO 59 YEARS', 'ESTIMATE PERCENT TOTAL POPULATION - 60 TO 64 YEARS', 'MOE PERCENT TOTAL POPULATION - 60 TO 64 YEARS', 'ESTIMATE PERCENT TOTAL POPULATION - 65 TO 69 YEARS', 'MOE PERCENT TOTAL POPULATION - 65 TO 69 YEARS', 'ESTIMATE PERCENT TOTAL POPULATION - 70 TO 74 YEARS', 'MOE PERCENT TOTAL POPULATION - 70 TO 74 YEARS', 'ESTIMATE PERCENT TOTAL POPULATION - 75 TO 79 YEARS', 'MOE PERCENT TOTAL POPULATION - 75 TO 79 YEARS', 'ESTIMATE PERCENT TOTAL POPULATION - 80 TO 84 YEARS', 'MOE PERCENT TOTAL POPULATION - 80 TO 84 YEARS', 'ESTIMATE PERCENT TOTAL POPULATION - 85 YEARS AND OVER', 'MOE PERCENT TOTAL POPULATION - 85 YEARS AND OVER', 'ESTIMATE PERCENT TOTAL POPULATION - 5 TO 14 YEARS', 'MOE PERCENT TOTAL POPULATION - 5 TO 14 YEARS', 'ESTIMATE PERCENT TOTAL POPULATION - 15 TO 17 YEARS', 'MOE PERCENT TOTAL POPULATION - 15 TO 17 YEARS', 'ESTIMATE PERCENT TOTAL POPULATION - UNDER 18 YEARS', 'MOE PERCENT TOTAL POPULATION - UNDER 18 YEARS', 'ESTIMATE PERCENT TOTAL POPULATION - 18 TO 24 YEARS', 'MOE PERCENT TOTAL POPULATION - 18 TO 24 YEARS', 'ESTIMATE PERCENT TOTAL POPULATION - 15 TO 44 YEARS', 'MOE PERCENT TOTAL POPULATION - 15 TO 44 YEARS', 'ESTIMATE PERCENT TOTAL POPULATION - 16 YEARS AND OVER', 'MOE PERCENT TOTAL POPULATION - 16 YEARS AND OVER', 'ESTIMATE PERCENT TOTAL POPULATION - 18 YEARS AND OVER', 'MOE PERCENT TOTAL POPULATION - 18 YEARS AND OVER', 'ESTIMATE PERCENT TOTAL POPULATION - 21 YEARS AND OVER', 'MOE PERCENT TOTAL POPULATION - 21 YEARS AND OVER', 'ESTIMATE PERCENT TOTAL POPULATION - 60 YEARS AND OVER', 'MOE PERCENT TOTAL POPULATION - 60 YEARS AND OVER', 'ESTIMATE PERCENT TOTAL POPULATION - 62 YEARS AND OVER', 'MOE PERCENT TOTAL POPULATION - 62 YEARS AND OVER', 'ESTIMATE PERCENT TOTAL POPULATION - 65 YEARS AND OVER', 'MOE PERCENT TOTAL POPULATION - 65 YEARS AND OVER', 'ESTIMATE PERCENT TOTAL POPULATION - 75 YEARS AND OVER', 'MOE PERCENT TOTAL POPULATION - 75 YEARS AND OVER', 'ESTIMATE PERCENT TOTAL POPULATION - SEX', 'ESTIMATE PERCENT TOTAL POPULATION - AGE', 'ESTIMATE MALE TOTAL POPULATION', 'MOE MALE TOTAL POPULATION', 'ESTIMATE MALE TOTAL POPULATION - UNDER 5 YEARS', 'MOE MALE TOTAL POPULATION - UNDER 5 YEARS', 'ESTIMATE MALE TOTAL POPULATION - 5 TO 9 YEARS', 'MOE MALE TOTAL POPULATION - 5 TO 9 YEARS', 'ESTIMATE MALE TOTAL POPULATION - 10 TO 14 YEARS', 'MOE MALE TOTAL POPULATION - 10 TO 14 YEARS', 'ESTIMATE MALE TOTAL POPULATION - 15 TO 19 YEARS', 'MOE MALE TOTAL POPULATION - 15 TO 19 YEARS', 'ESTIMATE MALE TOTAL POPULATION - 20 TO 24 YEARS', 'MOE MALE TOTAL POPULATION - 20 TO 24 YEARS', 'ESTIMATE MALE TOTAL POPULATION - 25 TO 29 YEARS', 'MOE MALE TOTAL POPULATION - 25 TO 29 YEARS', 'ESTIMATE MALE TOTAL POPULATION - 30 TO 34 YEARS', 'MOE MALE TOTAL POPULATION - 30 TO 34 YEARS', 'ESTIMATE MALE TOTAL POPULATION - 35 TO 39 YEARS', 'MOE MALE TOTAL POPULATION - 35 TO 39 YEARS', 'ESTIMATE MALE TOTAL POPULATION - 40 TO 44 YEARS', 'MOE MALE TOTAL POPULATION - 40 TO 44 YEARS', 'ESTIMATE MALE TOTAL POPULATION - 45 TO 49 YEARS', 'MOE MALE TOTAL POPULATION - 45 TO 49 YEARS', 'ESTIMATE MALE TOTAL POPULATION - 50 TO 54 YEARS', 'MOE MALE TOTAL POPULATION - 50 TO 54 YEARS', 'ESTIMATE MALE TOTAL POPULATION - 55 TO 59 YEARS', 'MOE MALE TOTAL POPULATION - 55 TO 59 YEARS', 'ESTIMATE MALE TOTAL POPULATION - 60 TO 64 YEARS', 'MOE MALE TOTAL POPULATION - 60 TO 64 YEARS', 'ESTIMATE MALE TOTAL POPULATION - 65 TO 69 YEARS', 'MOE MALE TOTAL POPULATION - 65 TO 69 YEARS', 'ESTIMATE MALE TOTAL POPULATION - 70 TO 74 YEARS', 'MOE MALE TOTAL POPULATION - 70 TO 74 YEARS', 'ESTIMATE MALE TOTAL POPULATION - 75 TO 79 YEARS', 'MOE MALE TOTAL POPULATION - 75 TO 79 YEARS', 'ESTIMATE MALE TOTAL POPULATION - 80 TO 84 YEARS', 'MOE MALE TOTAL POPULATION - 80 TO 84 YEARS', 'ESTIMATE MALE TOTAL POPULATION - 85 YEARS AND OVER', 'MOE MALE TOTAL POPULATION - 85 YEARS AND OVER', 'ESTIMATE MALE TOTAL POPULATION - 5 TO 14 YEARS', 'MOE MALE TOTAL POPULATION - 5 TO 14 YEARS', 'ESTIMATE MALE TOTAL POPULATION - 15 TO 17 YEARS', 'MOE MALE TOTAL POPULATION - 15 TO 17 YEARS', 'ESTIMATE MALE TOTAL POPULATION - UNDER 18 YEARS', 'MOE MALE TOTAL POPULATION - UNDER 18 YEARS', 'ESTIMATE MALE TOTAL POPULATION - 18 TO 24 YEARS', 'MOE MALE TOTAL POPULATION - 18 TO 24 YEARS', 'ESTIMATE MALE TOTAL POPULATION - 15 TO 44 YEARS', 'MOE MALE TOTAL POPULATION - 15 TO 44 YEARS', 'ESTIMATE MALE TOTAL POPULATION - 16 YEARS AND OVER', 'MOE MALE TOTAL POPULATION - 16 YEARS AND OVER', 'ESTIMATE MALE TOTAL POPULATION - 18 YEARS AND OVER', 'MOE MALE TOTAL POPULATION - 18 YEARS AND OVER', 'ESTIMATE MALE TOTAL POPULATION - 21 YEARS AND OVER', 'MOE MALE TOTAL POPULATION - 21 YEARS AND OVER', 'ESTIMATE MALE TOTAL POPULATION - 60 YEARS AND OVER', 'MOE MALE TOTAL POPULATION - 60 YEARS AND OVER', 'ESTIMATE MALE TOTAL POPULATION - 62 YEARS AND OVER', 'MOE MALE TOTAL POPULATION - 62 YEARS AND OVER', 'ESTIMATE MALE TOTAL POPULATION - 65 YEARS AND OVER', 'MOE MALE TOTAL POPULATION - 65 YEARS AND OVER', 'ESTIMATE MALE TOTAL POPULATION - 75 YEARS AND OVER', 'MOE MALE TOTAL POPULATION - 75 YEARS AND OVER', 'ESTIMATE MALE TOTAL POPULATION - MEDIAN AGE (YEARS)', 'MOE MALE TOTAL POPULATION - MEDIAN AGE (YEARS)', 'ESTIMATE PERCENT MALE TOTAL POPULATION - UNDER 5 YEARS', 'MOE PERCENT MALE TOTAL POPULATION - UNDER 5 YEARS', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 5 TO 9 YEARS', 'MOE PERCENT MALE TOTAL POPULATION - 5 TO 9 YEARS', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 10 TO 14 YEARS', 'MOE PERCENT MALE TOTAL POPULATION - 10 TO 14 YEARS', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 15 TO 19 YEARS', 'MOE PERCENT MALE TOTAL POPULATION - 15 TO 19 YEARS', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 20 TO 24 YEARS', 'MOE PERCENT MALE TOTAL POPULATION - 20 TO 24 YEARS', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 25 TO 29 YEARS', 'MOE PERCENT MALE TOTAL POPULATION - 25 TO 29 YEARS', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 30 TO 34 YEARS', 'MOE PERCENT MALE TOTAL POPULATION - 30 TO 34 YEARS', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 35 TO 39 YEARS', 'MOE PERCENT MALE TOTAL POPULATION - 35 TO 39 YEARS', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 40 TO 44 YEARS', 'MOE PERCENT MALE TOTAL POPULATION - 40 TO 44 YEARS', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 45 TO 49 YEARS', 'MOE PERCENT MALE TOTAL POPULATION - 45 TO 49 YEARS', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 50 TO 54 YEARS', 'MOE PERCENT MALE TOTAL POPULATION - 50 TO 54 YEARS', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 55 TO 59 YEARS', 'MOE PERCENT MALE TOTAL POPULATION - 55 TO 59 YEARS', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 60 TO 64 YEARS', 'MOE PERCENT MALE TOTAL POPULATION - 60 TO 64 YEARS', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 65 TO 69 YEARS', 'MOE PERCENT MALE TOTAL POPULATION - 65 TO 69 YEARS', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 70 TO 74 YEARS', 'MOE PERCENT MALE TOTAL POPULATION - 70 TO 74 YEARS', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 75 TO 79 YEARS', 'MOE PERCENT MALE TOTAL POPULATION - 75 TO 79 YEARS', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 80 TO 84 YEARS', 'MOE PERCENT MALE TOTAL POPULATION - 80 TO 84 YEARS', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 85 YEARS AND OVER', 'MOE PERCENT MALE TOTAL POPULATION - 85 YEARS AND OVER', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 5 TO 14 YEARS', 'MOE PERCENT MALE TOTAL POPULATION - 5 TO 14 YEARS', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 15 TO 17 YEARS', 'MOE PERCENT MALE TOTAL POPULATION - 15 TO 17 YEARS', 'ESTIMATE PERCENT MALE TOTAL POPULATION - UNDER 18 YEARS', 'MOE PERCENT MALE TOTAL POPULATION - UNDER 18 YEARS', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 18 TO 24 YEARS', 'MOE PERCENT MALE TOTAL POPULATION - 18 TO 24 YEARS', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 15 TO 44 YEARS', 'MOE PERCENT MALE TOTAL POPULATION - 15 TO 44 YEARS', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 16 YEARS AND OVER', 'MOE PERCENT MALE TOTAL POPULATION - 16 YEARS AND OVER', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 18 YEARS AND OVER', 'MOE PERCENT MALE TOTAL POPULATION - 18 YEARS AND OVER', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 21 YEARS AND OVER', 'MOE PERCENT MALE TOTAL POPULATION - 21 YEARS AND OVER', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 60 YEARS AND OVER', 'MOE PERCENT MALE TOTAL POPULATION - 60 YEARS AND OVER', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 62 YEARS AND OVER', 'MOE PERCENT MALE TOTAL POPULATION - 62 YEARS AND OVER', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 65 YEARS AND OVER', 'MOE PERCENT MALE TOTAL POPULATION - 65 YEARS AND OVER', 'ESTIMATE PERCENT MALE TOTAL POPULATION - 75 YEARS AND OVER', 'MOE PERCENT MALE TOTAL POPULATION - 75 YEARS AND OVER', 'ESTIMATE FEMALE TOTAL POPULATION', 'MOE FEMALE TOTAL POPULATION', 'ESTIMATE FEMALE TOTAL POPULATION - UNDER 5 YEARS', 'MOE FEMALE TOTAL POPULATION - UNDER 5 YEARS', 'ESTIMATE FEMALE TOTAL POPULATION - 5 TO 9 YEARS', 'MOE FEMALE TOTAL POPULATION - 5 TO 9 YEARS', 'ESTIMATE FEMALE TOTAL POPULATION - 10 TO 14 YEARS', 'MOE FEMALE TOTAL POPULATION - 10 TO 14 YEARS', 'ESTIMATE FEMALE TOTAL POPULATION - 15 TO 19 YEARS', 'MOE FEMALE TOTAL POPULATION - 15 TO 19 YEARS', 'ESTIMATE FEMALE TOTAL POPULATION - 20 TO 24 YEARS', 'MOE FEMALE TOTAL POPULATION - 20 TO 24 YEARS', 'ESTIMATE FEMALE TOTAL POPULATION - 25 TO 29 YEARS', 'MOE FEMALE TOTAL POPULATION - 25 TO 29 YEARS', 'ESTIMATE FEMALE TOTAL POPULATION - 30 TO 34 YEARS', 'MOE FEMALE TOTAL POPULATION - 30 TO 34 YEARS', 'ESTIMATE FEMALE TOTAL POPULATION - 35 TO 39 YEARS', 'MOE FEMALE TOTAL POPULATION - 35 TO 39 YEARS', 'ESTIMATE FEMALE TOTAL POPULATION - 40 TO 44 YEARS', 'MOE FEMALE TOTAL POPULATION - 40 TO 44 YEARS', 'ESTIMATE FEMALE TOTAL POPULATION - 45 TO 49 YEARS', 'MOE FEMALE TOTAL POPULATION - 45 TO 49 YEARS', 'ESTIMATE FEMALE TOTAL POPULATION - 50 TO 54 YEARS', 'MOE FEMALE TOTAL POPULATION - 50 TO 54 YEARS', 'ESTIMATE FEMALE TOTAL POPULATION - 55 TO 59 YEARS', 'MOE FEMALE TOTAL POPULATION - 55 TO 59 YEARS', 'ESTIMATE FEMALE TOTAL POPULATION - 60 TO 64 YEARS', 'MOE FEMALE TOTAL POPULATION - 60 TO 64 YEARS', 'ESTIMATE FEMALE TOTAL POPULATION - 65 TO 69 YEARS', 'MOE FEMALE TOTAL POPULATION - 65 TO 69 YEARS', 'ESTIMATE FEMALE TOTAL POPULATION - 70 TO 74 YEARS', 'MOE FEMALE TOTAL POPULATION - 70 TO 74 YEARS', 'ESTIMATE FEMALE TOTAL POPULATION - 75 TO 79 YEARS', 'MOE FEMALE TOTAL POPULATION - 75 TO 79 YEARS', 'ESTIMATE FEMALE TOTAL POPULATION - 80 TO 84 YEARS', 'MOE FEMALE TOTAL POPULATION - 80 TO 84 YEARS', 'ESTIMATE FEMALE TOTAL POPULATION - 85 YEARS AND OVER', 'MOE FEMALE TOTAL POPULATION - 85 YEARS AND OVER', 'ESTIMATE FEMALE TOTAL POPULATION - 5 TO 14 YEARS', 'MOE FEMALE TOTAL POPULATION - 5 TO 14 YEARS', 'ESTIMATE FEMALE TOTAL POPULATION - 15 TO 17 YEARS', 'MOE FEMALE TOTAL POPULATION - 15 TO 17 YEARS', 'ESTIMATE FEMALE TOTAL POPULATION - UNDER 18 YEARS', 'MOE FEMALE TOTAL POPULATION - UNDER 18 YEARS', 'ESTIMATE FEMALE TOTAL POPULATION - 18 TO 24 YEARS', 'MOE FEMALE TOTAL POPULATION - 18 TO 24 YEARS', 'ESTIMATE FEMALE TOTAL POPULATION - 15 TO 44 YEARS', 'MOE FEMALE TOTAL POPULATION - 15 TO 44 YEARS', 'ESTIMATE FEMALE TOTAL POPULATION - 16 YEARS AND OVER', 'MOE FEMALE TOTAL POPULATION - 16 YEARS AND OVER', 'ESTIMATE FEMALE TOTAL POPULATION - 18 YEARS AND OVER', 'MOE FEMALE TOTAL POPULATION - 18 YEARS AND OVER', 'ESTIMATE FEMALE TOTAL POPULATION - 21 YEARS AND OVER', 'MOE FEMALE TOTAL POPULATION - 21 YEARS AND OVER', 'ESTIMATE FEMALE TOTAL POPULATION - 60 YEARS AND OVER', 'MOE FEMALE TOTAL POPULATION - 60 YEARS AND OVER', 'ESTIMATE FEMALE TOTAL POPULATION - 62 YEARS AND OVER', 'MOE FEMALE TOTAL POPULATION - 62 YEARS AND OVER', 'ESTIMATE FEMALE TOTAL POPULATION - 65 YEARS AND OVER', 'MOE FEMALE TOTAL POPULATION - 65 YEARS AND OVER', 'ESTIMATE FEMALE TOTAL POPULATION - 75 YEARS AND OVER', 'MOE FEMALE TOTAL POPULATION - 75 YEARS AND OVER', 'ESTIMATE FEMALE TOTAL POPULATION - MEDIAN AGE (YEARS)', 'MOE FEMALE TOTAL POPULATION - MEDIAN AGE (YEARS)', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - UNDER 5 YEARS', 'MOE PERCENT FEMALE TOTAL POPULATION - UNDER 5 YEARS', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 5 TO 9 YEARS', 'MOE PERCENT FEMALE TOTAL POPULATION - 5 TO 9 YEARS', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 10 TO 14 YEARS', 'MOE PERCENT FEMALE TOTAL POPULATION - 10 TO 14 YEARS', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 15 TO 19 YEARS', 'MOE PERCENT FEMALE TOTAL POPULATION - 15 TO 19 YEARS', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 20 TO 24 YEARS', 'MOE PERCENT FEMALE TOTAL POPULATION - 20 TO 24 YEARS', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 25 TO 29 YEARS', 'MOE PERCENT FEMALE TOTAL POPULATION - 25 TO 29 YEARS', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 30 TO 34 YEARS', 'MOE PERCENT FEMALE TOTAL POPULATION - 30 TO 34 YEARS', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 35 TO 39 YEARS', 'MOE PERCENT FEMALE TOTAL POPULATION - 35 TO 39 YEARS', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 40 TO 44 YEARS', 'MOE PERCENT FEMALE TOTAL POPULATION - 40 TO 44 YEARS', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 45 TO 49 YEARS', 'MOE PERCENT FEMALE TOTAL POPULATION - 45 TO 49 YEARS', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 50 TO 54 YEARS', 'MOE PERCENT FEMALE TOTAL POPULATION - 50 TO 54 YEARS', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 55 TO 59 YEARS', 'MOE PERCENT FEMALE TOTAL POPULATION - 55 TO 59 YEARS', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 60 TO 64 YEARS', 'MOE PERCENT FEMALE TOTAL POPULATION - 60 TO 64 YEARS', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 65 TO 69 YEARS', 'MOE PERCENT FEMALE TOTAL POPULATION - 65 TO 69 YEARS', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 70 TO 74 YEARS', 'MOE PERCENT FEMALE TOTAL POPULATION - 70 TO 74 YEARS', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 75 TO 79 YEARS', 'MOE PERCENT FEMALE TOTAL POPULATION - 75 TO 79 YEARS', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 80 TO 84 YEARS', 'MOE PERCENT FEMALE TOTAL POPULATION - 80 TO 84 YEARS', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 85 YEARS AND OVER', 'MOE PERCENT FEMALE TOTAL POPULATION - 85 YEARS AND OVER', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 5 TO 14 YEARS', 'MOE PERCENT FEMALE TOTAL POPULATION - 5 TO 14 YEARS', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 15 TO 17 YEARS', 'MOE PERCENT FEMALE TOTAL POPULATION - 15 TO 17 YEARS', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - UNDER 18 YEARS', 'MOE PERCENT FEMALE TOTAL POPULATION - UNDER 18 YEARS', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 18 TO 24 YEARS', 'MOE PERCENT FEMALE TOTAL POPULATION - 18 TO 24 YEARS', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 15 TO 44 YEARS', 'MOE PERCENT FEMALE TOTAL POPULATION - 15 TO 44 YEARS', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 16 YEARS AND OVER', 'MOE PERCENT FEMALE TOTAL POPULATION - 16 YEARS AND OVER', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 18 YEARS AND OVER', 'MOE PERCENT FEMALE TOTAL POPULATION - 18 YEARS AND OVER', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 21 YEARS AND OVER', 'MOE PERCENT FEMALE TOTAL POPULATION - 21 YEARS AND OVER', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 60 YEARS AND OVER', 'MOE PERCENT FEMALE TOTAL POPULATION - 60 YEARS AND OVER', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 62 YEARS AND OVER', 'MOE PERCENT FEMALE TOTAL POPULATION - 62 YEARS AND OVER', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 65 YEARS AND OVER', 'MOE PERCENT FEMALE TOTAL POPULATION - 65 YEARS AND OVER', 'ESTIMATE PERCENT FEMALE TOTAL POPULATION - 75 YEARS AND OVER', 'MOE PERCENT FEMALE TOTAL POPULATION - 75 YEARS AND OVER']
target_column = 'PostalCode.Count'

# Step 1: Calculate PostalCode counts for the entire dataset
postal_code_counts = pd.Series(dtype='int64')

for chunk in pd.read_csv(file_path, chunksize=chunksize, low_memory=False):
    postal_code_counts = postal_code_counts.add(chunk['POSTALCODE'].value_counts(), fill_value=0)

postal_code_counts = postal_code_counts.astype(int)

# Step 2: Process the data in chunks and add PostalCode.Count column
X_full = pd.DataFrame()
y_full = pd.Series(dtype='float64')

for chunk in pd.read_csv(file_path, chunksize=chunksize, low_memory=False):
    # Drop unnecessary columns
    chunk = chunk.drop(columns=columns_to_drop, errors='ignore')
    
    # Assign PostalCode.Count column
    chunk['PostalCode.Count'] = chunk['POSTALCODE'].map(postal_code_counts)
    
    # Append to main DataFrame
    X_full = pd.concat([X_full, chunk[demographic_columns]], ignore_index=True)
    y_full = pd.concat([y_full, chunk[target_column]], ignore_index=True)

X_full.fillna(X_full.median(), inplace=True)
# Remove rows where y_full has NaN values
valid_indices = y_full.notna()
X_full = X_full[valid_indices]
y_full = y_full[valid_indices]

X_train, X_test, y_train, y_test = train_test_split(X_full, y_full, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"Number of NaNs in y_full: {y_full.isna().sum()}")

lr_model = LinearRegression()
lr_model.fit(X_train_scaled, y_train)

lr_preds = lr_model.predict(X_test_scaled)

print("\nLinear Regression Performance:")
print(f"Mean Squared Error: {mean_squared_error(y_test, lr_preds)}")
print(f"Mean Absolute Error: {mean_absolute_error(y_test, lr_preds)}")
print(f"R^2 Score: {r2_score(y_test, lr_preds)}")

from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train_scaled, y_train)
rf_preds = rf_model.predict(X_test_scaled)

print("\nRandom Forest Performance:")
print(f"Mean Squared Error: {mean_squared_error(y_test, rf_preds)}")
print(f"Mean Absolute Error: {mean_absolute_error(y_test, rf_preds)}")
print(f"R^2 Score: {r2_score(y_test, rf_preds)}")


from joblib import dump, load

# Save the model to a file
dump(rf_model, 'random_forest_model.joblib')
print("Model saved!")

# Load the saved model
loaded_model = load('random_forest_model.joblib')
print("Model loaded successfully!")

import matplotlib.pyplot as plt

# Assuming you have feature names in a list called `feature_names`
feature_names = X_train.columns if hasattr(X_train, 'columns') else [f"Feature {i}" for i in range(X_train.shape[1])]

# Get feature importances
feature_importances = loaded_model.feature_importances_

# Create a DataFrame for better visualization
importance_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': feature_importances
}).sort_values(by='Importance', ascending=False)

# Slice to get the top 20 features
top_20_features = importance_df.head(20)

# Display top features
print(top_20_features)

# Plot feature importances for the top 20 features
plt.figure(figsize=(10, 6))
plt.barh(top_20_features['Feature'], top_20_features['Importance'])
plt.gca().invert_yaxis()
plt.title("Top 20 Feature Importance")
plt.xlabel("Importance")
plt.ylabel("Features")
plt.show()

from sklearn.tree import export_graphviz

import graphviz

# Export one tree from the Random Forest
tree = loaded_model.estimators_[0]
dot_data = export_graphviz(tree, out_file=None, 
                           feature_names=feature_names, 
                           filled=True, rounded=True, 
                           special_characters=True)

# Visualize the tree
graph = graphviz.Source(dot_data)
graph.render("random_forest_tree")  # Saves the tree visualization as a PDF file
graph.view()  # Opens the tree visualization

scaler.fit(X_train)  # Fit the scaler on the training data

# Save the scaler for future use
dump(scaler, 'scaler.joblib')
print("Scaler saved successfully!")

# Display the columns used during scaler fitting
fit_columns = scaler.feature_names_in_
print("Columns used during scaler fitting:")
print(fit_columns)

# Define chunk size
chunk_size = 10000  # Adjust based on memory capacity

# Load the saved model and scaler
loaded_model = load('random_forest_model.joblib')
scaler = load('scaler.joblib')

# Display the columns used during scaler fitting
fit_columns = scaler.feature_names_in_

# Open output file and write header
header_written = False

# Process the dataset in chunks
for chunk in pd.read_csv(input_file, chunksize=chunk_size):
    print(f"Processing chunk...")

    # Standardize column names to match the training dataset
    chunk.columns = chunk.columns.str.strip().str.upper()

    # Extract ZIP_CODE column as an identifier
    zip_codes = chunk['ZIP_CODE'] if 'ZIP_CODE' in chunk.columns else None

    # Prepare the data for scaling and prediction
    data_to_scale = chunk.drop(columns=['ZIP_CODE'], errors='ignore')

    # Ensure all features used during training are present in the chunk
    expected_columns = [col.strip().upper() for col in fit_columns]
    data_to_scale = data_to_scale.reindex(columns=expected_columns, fill_value=0)

    # Scale the data
    X_chunk_scaled = scaler.transform(data_to_scale)

    # Make predictions
    y_pred_chunk = loaded_model.predict(X_chunk_scaled)

    # Create the DataFrame for predictions
    predictions = pd.DataFrame({
        'ZIP_CODE': zip_codes.values if zip_codes is not None else [None] * len(y_pred_chunk),
        'PREDICTED_TARGET': y_pred_chunk
    })
    
    # Save predictions to the file with only the required columns
    predictions[['ZIP_CODE', 'PREDICTED_TARGET']].to_csv(output_file, mode='a', index=False, header=not header_written)
    header_written = True  # Ensure the header is written only once

print("\nProcessing complete. Predictions saved to:", output_file)
